### ISSUE TITLE
fibocom_MHI 6.1内核报错 pcie_mhi_fb-3.2/core/mhi_boot.c:212:23: error: implicit declaration of function 'prandom_u32';

### ISSUE THREAD

**Issue by suyuan168** [Siriling/5G-Modem-Support#1]
prandom_u32_max
sequence_id = prandom_u32() & BHIE_RXVECSTATUS_SEQNUM_BMSK;

pcie_mhi_fb-3.2/core/mhi_boot.c:212:23: error: implicit declaration of function 'prandom_u32'; did you mean 'prandom_u32_max'? [-Werror=implicit-function-declaration]
  212 |         sequence_id = prandom_u32() & BHIE_RXVECSTATUS_SEQNUM_BMSK;
      |                       ^~~~~~~~~~~
      |                       prandom_u32_max
cc1: some warnings being treated as errors

**Comment by Siriling** [comment]
广和通的驱动没人修，多数人都是用移远的。广和通模块用移远PCIE驱动也可以的
