### ISSUE TITLE
RSSI progress bar missing.

### ISSUE THREAD

**Issue by mdsdtech** [Siriling/5G-Modem-Support#10]
RSSI meter bar not showing or missing.

![Screenshot from 2024-05-22 21-23-34](https://github.com/Siriling/5G-Modem-Support/assets/70020155/f9370496-f3a7-45da-8918-49a646e81b63)

**Comment by Siriling** [comment]
RSSI 还未添加上信号条显示，后续会加上

**Comment by mdsdtech** [comment]
Ah, I see, thank you for your work. Can wait to trying the next releases.
