### ISSUE TITLE
能否针对掉模块、断网等情况 添加一些自动重连、重启的机制？

### ISSUE THREAD

**Issue by SebaSs007** [Siriling/5G-Modem-Support#11]
有的设备在使用模块时，由于多种多样的原因，会在使用一段时间后突然断网，插件配置页里  模块名称、配置串口都消失了，仅有网络列还有内容，日志里也显示【NETDEV WATCHDOG: eth3 (rndis_host): transmit queue 0 timed out】所以我判断是模块和设备发生了中断。

发生频率不高，但是想要重连则需要去后台重新“扫描模组”，并重新关闭和启用一次拨号配置，以此来恢复。

目前使用固件是你定制云编译的istoreos，设备主要使用的模块是fm350gl

此外还有一个设备在使用时，显示已连接、信号正常，但就是没网  需要关闭和启用拨号配置 才恢复。

我不清楚这种情况是不是特例，但是希望能否针对 掉模块、断网 等情况 推出一个应对机制？

**Comment by SebaSs007** [comment]
目前使用固件是你定制 云编译的istoreos，设备主要使用的模块是fm350gl

**Comment by Siriling** [comment]
一直都有对断网情况做过处理，断网重连支持的。你的情况大概率是掉模块，掉模块一般是供电不够，需要检查模块供电是否正常（电压大于3.8V）。

**Comment by Siriling** [comment]
关于模块连接状态判断一直没有很完美的方法，目前通过IP来进行判断。
如果模块已经获取到了IP，但是无法上网，此时应该确认是模块的问题，重新拨号或者重启模块。

**Comment by SebaSs007** [comment]
是的，我判断是供电不稳定导致的掉模块问题，但是供电问题无法解决。
能否在一定时间间隔下 ping 指定IP 进行判断判断，比如一些公共dns，从而判断是否需要重新拨号？

**Comment by Siriling** [comment]
硬件问题不能解决，指望软件给你解决吗？

- 就算软件解决了，你每重新配置，重新拨号一次时间都很长，你能很明显感知到断网了

- 长期供电不足会损坏模块

**Comment by SebaSs007** [comment]
@Siriling  软件没法完美解决这我是明白的，有明显感知也是清楚的，本身这种情况出现后也需要去后台启停恢复。
不过是希望软件上有个这种功能减少人工去启停的操作。
我手上这个设备据说是设计问题 偶尔才会出现不稳定的情况   不是长时间的。

比如中兴U50S 这个产品有个 看门狗功能，也是通过ping指定站点判断设备是否断网，如果断网超过一定时间会直接重启设备。
有些三方固件里的拨号工具也有类似功能，所以才建议添加下。
