### ISSUE TITLE
f350重启路由后，无法自动勾选拨号

### ISSUE THREAD

**Issue by AIGeekMaker** [Siriling/5G-Modem-Support#19]
f350重启路由后，无法自动勾选拨号，即使我已经设置好了运营商
出现在瓜皮v3，多模块场景

**Comment by Siriling** [comment]
> f350重启路由后，无法自动勾选拨号，即使我已经设置好了运营商 出现在瓜皮v3，多模块场景

具体几个模块同时使用？
分别是什么模块？
是否有尝试开启手动配置？

**Comment by AIGeekMaker** [comment]
> > f350重启路由后，无法自动勾选拨号，即使我已经设置好了运营商 出现在瓜皮v3，多模块场景
> 
> 具体几个模块同时使用？ 分别是什么模块？ 是否有尝试开启手动配置？

共计有3个模块使用
如图所示，断电重启后，只有rm500q是会自动启动，而其余两个fm350-gl都勾都没有打上
没有开启手动配置
![image](https://github.com/user-attachments/assets/14fd1cb3-090a-44ba-8a7c-20a517d859ac)

**Comment by AIGeekMaker** [comment]
> > f350重启路由后，无法自动勾选拨号，即使我已经设置好了运营商 出现在瓜皮v3，多模块场景
> 
> 具体几个模块同时使用？ 分别是什么模块？ 是否有尝试开启手动配置？

共计有3个模块使用
如图所示，断电重启后，只有rm500q是会自动启动，而其余两个fm350-gl都勾都没有打上
没有开启手动配置

![image](https://github.com/user-attachments/assets/488de150-93da-44c1-8fe4-683c5e1b8048)

**Comment by Siriling** [comment]
如果模块不变动的话，可以开启手动配置尝试

**Comment by Siriling** [comment]
> > > f350重启路由后，无法自动勾选拨号，即使我已经设置好了运营商 出现在瓜皮v3，多模块场景
> > 
> > 
> > 具体几个模块同时使用？ 分别是什么模块？ 是否有尝试开启手动配置？
> 
> 共计有3个模块使用 如图所示，断电重启后，只有rm500q是会自动启动，而其余两个fm350-gl都勾都没有打上 没有开启手动配置
> 
> ![image](https://private-user-images.githubusercontent.com/149160237/364610041-488de150-93da-44c1-8fe4-683c5e1b8048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NjU2MDksIm5iZiI6MTcyNTc2NTMwOSwicGF0aCI6Ii8xNDkxNjAyMzcvMzY0NjEwMDQxLTQ4OGRlMTUwLTkzZGEtNDRjMS04ZmU0LTY4M2M1ZTFiODA0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwMzE1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjhhMTdkYTY4ZThkNzNiNTk4NTc5ZmMwZWMzZTU2M2YyODViNDU1M2M1NmE3OWRkOThlYzk0NGNlZjA3ZjY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tNmX5ykhA2nKFkPw_-VwVsTwpSrZBlNFZaHkpXFpD_4)

如果模块不变动的话，可以开启手动配置尝试

**Comment by AIGeekMaker** [comment]
![image](https://github.com/user-attachments/assets/aaeefad5-1eef-40be-80de-43cdc9bd0da5)
已经勾选了，不过断电重启以后还是只能勾选一块，发现不一定是rm500-gl，估计是轮询到有识别到一块的时候就直接拨号了？然后轮询停止，是这样吗
![image](https://github.com/user-attachments/assets/0957e6be-05ed-42b4-bea2-227976c6d235)

**Comment by AIGeekMaker** [comment]
是不是要加个启动后延时的选项，我估计是因为350在瓜皮上需要几十秒才能识别出来导致的，500q是秒识别的

**Comment by AIGeekMaker** [comment]
get_modems方法

**Comment by zhou1407** [comment]
重启后读不出模块我也有遇到过，我的解决办法是把启动项优先级从90改到99，变相延时启动

**Comment by AIGeekMaker** [comment]
> 重启后读不出模块我也有遇到过，我的解决办法是把启动项优先级从90改到99，变相延时启动

怎么改优先级，我看现在的modemInit优先级在70
![image](https://github.com/user-attachments/assets/9f4b0360-4139-49d0-b430-11e9f35013f1)

**Comment by Siriling** [comment]
由于FM350启动很慢导致的问题，特别是在ARM机器上很明显。
可以参照以下方法解决

1. 直接在命令行输入下面命令（前面20是上一次的数，如果还没有自动勾选，就继续改大后面的数）
```shell
sed -i 's/time=20/time=30/' /etc/init.d/modem
```
2. 修改文件/etc/init.d/modem，把图中20改为最小的能自动勾选的数
![3e502ff2e7d55dc40ab004b11ab46077](https://github.com/user-attachments/assets/e02969ed-33ff-468f-8717-5cd41383421e)

**Comment by zhou1407** [comment]
大佬，那这样是不是也可以修改启动项优先级啊，我之前是把启动项下载出来修改后再上传回去替换原文件的
