### ISSUE TITLE
没有提供mtk_pcie_wwan_m80驱动吗

### ISSUE THREAD

**Issue by sqliuchang** [Siriling/5G-Modem-Support#21]
没找到mtk_pcie_wwan_m80这个私有驱动，没法使用pcie通道的FM350

**Comment by Siriling** [comment]
> 没找到mtk_pcie_wwan_m80这个私有驱动，没法使用pcie通道的FM350

- 这是私有驱动，没有人找到过这个，靠大家找了。
- 现在FM350 PCIE都使用公有驱动，参考https://github.com/Siriling/5G-Modem-Support/issues/8

**Comment by sqliuchang** [comment]
> > 没找到mtk_pcie_wwan_m80这个私有驱动，没法使用pcie通道的FM350
> 
> * 这是私有驱动，没有人找到过这个，靠大家找了。
> * 现在FM350 PCIE都使用公有驱动，参考[请求广和通 FM350 Gl  Linux pcie模式 mtk_t7xx驱动支持 #8](https://github.com/Siriling/5G-Modem-Support/issues/8)

感谢，那我去试试

**Comment by sqliuchang** [comment]
看了下mtk_t7xx从6.1才开始引入，尝试之后发现没办法简单修改移植到5.15，再结合 https://github.com/Siriling/5G-Modem-Support/issues/3 ，所以目前要用pcie通道的fm350只能用6.1的内核
