### ISSUE TITLE
依赖grep导致其他软件异常

### ISSUE THREAD

**Issue by jjm2473** [Siriling/5G-Modem-Support#4]
luci-app-modem强制依赖了grep：
https://github.com/Siriling/5G-Modem-Support/blob/6dcc1416af91e9fea138ba28f5a7282cc91d7843/luci-app-modem/Makefile#L26

这个版本的grep会替换掉默认的busybox提供的grep，根据测试，反而支持的语法更少（例如不支持`\d`）。
对比测试:
```bash
echo '../path/usb2/2-2/2-2:0-0/' | grep -oE '/usb\d+/[^:]+'
echo '../path/usb2/2-2/2-2:0-0/' | busybox grep -oE '/usb\d+/[^:]+'
```

我搜索了一下你的代码 https://github.com/search?q=repo%3ASiriling%2F5G-Modem-Support+grep+path%3Aluci-app-modem&type=code

看起来也没使用特殊的grep语法，busybox提供的grep应该能满足你的需求。所以，尽量删掉grep依赖。

**Comment by Siriling** [comment]
modem确实需要grep，我添加是为了防止有些系统没有装这个依赖，会影响modem的正常工作，如果这个都有提供的话，可以删除

**Comment by jjm2473** [comment]
默认busybox都有提供，不需要依赖，而且依赖以后会安装gnu版本

**Comment by jjm2473** [comment]
openwrt固件默认都没安装grep，但是都可以调用grep命令，因为busybox已经提供了。不只是grep，还有sed也有。

**Comment by Siriling** [comment]
好的，如果有的话，那这个依赖就可以删除了

**Comment by Siriling** [comment]
我可以在依赖把grep换成busybox吗

**Comment by jjm2473** [comment]
应该不需要吧，busybox是系统基础的组建，要是没有busybox，系统升级都没法使用，并且busybox也是默认安装的。也不应该依赖busybox，busybox有selinux和非selinux的版本，没法确定用哪个。

**Comment by Siriling** [comment]
好的，那我就单纯去掉进行了，近期上传新版本，顺便把这个改了
