### ISSUE TITLE
缺少 kmod-pcie_mhi 依赖

### ISSUE THREAD

**Issue by 217heidai** [Siriling/5G-Modem-Support#7]
大佬，编译 luci-app-modem 提示缺少 kmod-pcie_mhi，咨询下 kmod-pcie_mhi 在哪个里面

**Comment by Siriling** [comment]
你漏了这个[quectel_MHI](https://github.com/Siriling/5G-Modem-Support/tree/main/quectel_MHI)

**Comment by 217heidai** [comment]
谢谢大佬！  
再咨询下，FM350-GL USB RNDIS 模式，编译 OpenWrt 只需要带上 [5G-Modem-Support](https://github.com/Siriling/5G-Modem-Support) 库里 luci-app-modem 和相关依赖就行吗，还要带其他插件吗？

**Comment by Siriling** [comment]
是的

**Comment by 217heidai** [comment]
可以编译了，谢谢大佬。  
FM350-GL USB RNDIS 模式，打包了 fibocom-dial，但是拨号工具配置里只能看到移远、调制解调器管理工具，没有广和通。  
选自动，拨号失败提示信息：
```
Send AT command AT+CGTACT=1,3 to modem
Unable to get IPv4 address
```

**Comment by Siriling** [comment]
FM350拨号不需要使用`fibocom-dial`。使用Modem时，在正确识别模块信息的情况下，直接添加个拨号配置就可以自动拨号了。

- 对FFM350不了解请查看：https://blog.siriling.com:1212/2023/04/12/5g-modem-fibocom-fm350-gl/
- 对Modem使用不了解请查看：https://blog.siriling.com:1212/2023/03/18/openwrt-5g-modem/#bo-hao-shang-wang-ji-shi-yong

**Comment by 217heidai** [comment]
谢谢大佬，问题解决了，是天线的问题。之前模块没插天线，导致拨号一直失败。
